tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask-fonts"

brew "tmux"
brew "zsh"
brew "neovim"
brew "ripgrep"
brew "bat"
brew "fd"
brew "fzf"
brew "git-delta"
brew "go"
brew "graphviz"
brew "wget"
cask "kitty"
cask "karabiner-elements"
cask "font-jetbrains-mono-nerd-font"
