export ZSH=~/.oh-my-zsh
export EDITOR=nvim


set -o vi

ZSH_THEME="simple"
plugins=(
  git
  docker
  docker-compose
  golang
  zsh-vi-mode
  zsh-autosuggestions
  fast-syntax-highlighting
  you-should-use
  web-search
  auto-notify
)

ZSH_WEB_SEARCH_ENGINES=(
  cambridge "https://dictionary.cambridge.org/dictionary/english/"
)

source $ZSH/oh-my-zsh.sh

export PATH=$HOME/.local/bin/:$PATH

if go env GOPATH 2>&1 > /dev/null; then
    export PATH=$PATH:$(go env GOPATH)/bin/
fi

alias vim=nvim
alias vi=vim
alias v=vi
alias cat=bat

if [[ "$(uname)" == 'Linux' ]]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi


PROMPT=$PROMPT$'%{%F{166}%}\u03bb%{%f%} '

_RPROMPT='%(?..%F{red}?%? )%F{white}%D{%H:%M}'
RPROMPT=$_RPROMPT

export FZF_DEFAULT_OPTS="--cycle --color=gutter:-1 --pointer '>' --border rounded --highlight-line"
export FZF_CTRL_R_OPTS='--height=100% --margin 15%'

zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')

function git-vimdiff () {
    GIT_EXTERNAL_DIFF=git-diff-wrapper git --no-pager diff $@;
}

function preexec() {
  timer=${timer:-$SECONDS}
}

function precmd() {
  if [ $timer ]; then
    timer_seconds=$(($SECONDS - $timer))
    _TIMER_PROMPT=''
    if [ $timer_seconds -gt 0 ]; then
        _TIMER_PROMPT='%F{cyan}~> '
        timer_minutes=$(($timer_seconds / 60))
        timer_seconds=$(($timer_seconds % 60))
        if [ $timer_minutes -gt 0 ]; then
            _TIMER_PROMPT=$_TIMER_PROMPT'${timer_minutes}m'
        fi
        _TIMER_PROMPT=$_TIMER_PROMPT'${timer_seconds}s '
    fi
    RPROMPT=$_TIMER_PROMPT$_RPROMPT
    unset timer
  fi
}

if [ -e ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi
