#!/usr/bin/env zsh

function prompt_aufforderung_setup() {
    zmodload zsh/datetime

    autoload -Uz vcs_info
    zstyle ':vcs_info:*' enable git
    zstyle ':vcs_info:*' formats '%b%u%c%f '
    zstyle ':vcs_info:*' actionformats '%F{red}[%a]%f %b '
    zstyle ':vcs_info:*' check-for-changes true
    zstyle ':vcs_info:*' stagedstr ' %F{green}+'
    zstyle ':vcs_info:*' unstagedstr ' %F{red}*'

    autoload -Uz add-zsh-hook
    add-zsh-hook precmd  prompt_aufforderung_precmd
    add-zsh-hook preexec prompt_aufforderung_preexec

    PS1='%F{green}%~%f %B%F{blue}${vcs_info_msg_0_}%f%b%F{166}λ%f '
    RPS1='${prompt_aufforderung_exec_time}%(?..%F{red}?%?%f )%F{white}%D{%H:%M}%f'

    prompt_opts=(cr subst percent sp)
}

function prompt_aufforderung_preexec() {
    _prompt_timer=$EPOCHREALTIME
}

function prompt_aufforderung_precmd() {
    if (( _prompt_timer )); then
        local -F elapsed=$(( EPOCHREALTIME - _prompt_timer ))

        if (( elapsed >= 1 )); then
            local -i secs=$(( elapsed ))
            local -i mins=$(( secs / 60 ))
            secs=$(( secs % 60 ))

            local out='%F{cyan}~> '
            (( mins > 0 )) && out+="${mins}m"
            out+="${secs}s%f "
            prompt_aufforderung_exec_time=$out
        else
            unset prompt_aufforderung_exec_time
        fi

        unset _prompt_timer
    else
        unset prompt_aufforderung_exec_time
    fi

    vcs_info
}

prompt_aufforderung_setup "$@"
