[note]
language = "en"
default-title = "Untitled"
filename = "{{slug title}}"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
shell = "/bin/zsh"
pager = "bat"
fzf-preview = "bat -p --color always {-1}"
