return {
  "nvim-treesitter/nvim-treesitter",
  event = "BufEnter",
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "html",
      "json",
      "lua",
      "yaml",
      "go",
      "gomod",
      "gosum",
      "markdown",
      "rust",
      "perl",
      "vue",
      "javascript",
      "java",
      "proto",
      "vim",
      "dot",
      "helm",
      "comment",
    },
    highlight = { enable = true },
    indent    = { enable = false },
  },
  config = function(_, opts)
    require("nvim-treesitter.configs").setup(opts)
  end,
}
